import { BrandAlias } from '@/stores/cosmetics';

export const initialBrands: BrandAlias[] = [
  { canonicalName: 'SHISEIDO', aliases: ['SHISEIDO', '資生堂'] },
  { canonicalName: 'CHANEL', aliases: ['CHANEL', 'シャネル'] },
  { canonicalName: 'Dior', aliases: ['Dior', 'ディオール'] },
  { canonicalName: 'KANEBO', aliases: ['KANEBO', 'カネボウ'] },
  { canonicalName: 'KOSE', aliases: ['KOSE', 'コーセー'] },
  { canonicalName: 'RMK', aliases: ['RMK'] },
  { canonicalName: 'ADDICTION', aliases: ['ADDICTION'] },
  { canonicalName: 'THREE', aliases: ['THREE'] },
  { canonicalName: 'SUQQU', aliases: ['SUQQU', 'スック'] },
  { canonicalName: 'Celvoke', aliases: ['Celvoke', 'セルヴォーク'] },
  { canonicalName: 'LUNASOL', aliases: ['LUNASOL', 'ルナソル'] },
  { canonicalName: 'Amplitude', aliases: ['Amplitude', 'アンプリチュード'] },
  { canonicalName: 'JILL STUART', aliases: ['JILL STUART', 'ジルスチュアート'] },
  { canonicalName: 'DECORTÉ', aliases: ['DECORTÉ', 'コスメデコルテ'] },
  { canonicalName: 'CLARINS', aliases: ['CLARINS', 'クラランス'] },
  { canonicalName: 'NARS', aliases: ['NARS', 'ナーズ'] },
  { canonicalName: 'M.A.C', aliases: ['M.A.C', 'マック'] },
  { canonicalName: 'BOBBI BROWN', aliases: ['BOBBI BROWN', 'ボビイ ブラウン'] },
  { canonicalName: 'LAURA MERCIER', aliases: ['LAURA MERCIER', 'ローラ メルシエ'] },
  { canonicalName: 'shu uemura', aliases: ['shu uemura', 'シュウ ウエムラ'] },
  { canonicalName: 'ESTEE LAUDER', aliases: ['ESTEE LAUDER', 'エスティ ローダー'] },
  { canonicalName: 'CLINIQUE', aliases: ['CLINIQUE', 'クリニーク'] },
  { canonicalName: 'GIVENCHY', aliases: ['GIVENCHY', 'ジバンシイ'] },
  { canonicalName: 'YVES SAINT LAURENT', aliases: ['YVES SAINT LAURENT', 'イヴ・サンローラン'] },
  { canonicalName: 'TOM FORD BEAUTY', aliases: ['TOM FORD BEAUTY', 'トム フォード ビューティ'] },
  { canonicalName: 'BYREDO', aliases: ['BYREDO', 'バイレード'] },
  { canonicalName: 'Jo Malone London', aliases: ['Jo Malone London', 'ジョー マローン ロンドン'] },
  { canonicalName: 'Aesop', aliases: ['Aesop', 'イソップ'] },
  { canonicalName: 'THREE', aliases: ['THREE', 'スリー'] },
  { canonicalName: 'Amplitude', aliases: ['Amplitude', 'アンプリチュード'] },
  { canonicalName: 'to/one', aliases: ['to/one', 'トーン'] },
  { canonicalName: 'SNIDEL BEAUTY', aliases: ['SNIDEL BEAUTY', 'スナイデル ビューティ'] },
  { canonicalName: 'Fenty Beauty', aliases: ['Fenty Beauty', 'フェンティ ビューティ'] },
  { canonicalName: 'Kylie Cosmetics', aliases: ['Kylie Cosmetics', 'カイリー コスメティクス'] },
  { canonicalName: 'Glossier', aliases: ['Glossier', 'グロッシアー'] },
  { canonicalName: 'Drunk Elephant', aliases: ['Drunk Elephant', 'ドランク エレファント'] },
  { canonicalName: 'The Ordinary', aliases: ['The Ordinary', 'ジ オーディナリー'] },
  { canonicalName: 'CeraVe', aliases: ['CeraVe', 'セラヴィ'] },
  { canonicalName: 'La Roche-Posay', aliases: ['La Roche-Posay', 'ラ ロッシュ ポゼ'] },
  
  { canonicalName: 'SK-II', aliases: ['SK-II', 'エスケーツー'] },
  { canonicalName: 'FANCL', aliases: ['FANCL', 'ファンケル'] },
  { canonicalName: 'ORBIS', aliases: ['ORBIS', 'オルビス'] },
  { canonicalName: 'HABA', aliases: ['HABA', 'ハーバー'] },
  { canonicalName: 'Attenir', aliases: ['Attenir', 'アテニア'] },
  { canonicalName: 'AMPLEUR', aliases: ['AMPLEUR', 'アンプルール'] },
  { canonicalName: 'Dr.Ci:Labo', aliases: ['Dr.Ci:Labo', 'ドクターシーラボ'] },
  { canonicalName: 'AMPLEUR', aliases: ['AMPLEUR', 'アンプルール'] },
  { canonicalName: 'Obagi', aliases: ['Obagi', 'オバジ'] },
  { canonicalName: 'Transino', aliases: ['Transino', 'トランシーノ'] },
  { canonicalName: 'MINON', aliases: ['MINON', 'ミノン'] },
  { canonicalName: 'Curel', aliases: ['Curel', 'キュレル'] },
  { canonicalName: 'd program', aliases: ['d program', 'dプログラム'] },
  { canonicalName: 'IHADA', aliases: ['IHADA', 'イハダ'] },
  { canonicalName: 'ANESSA', aliases: ['ANESSA', 'アネッサ'] },
  { canonicalName: 'ALLIE', aliases: ['ALLIE', 'アリィー'] },
  { canonicalName: 'Biore UV', aliases: ['Biore UV', 'ビオレUV'] },
  { canonicalName: 'SUNCUT', aliases: ['SUNCUT', 'サンカット'] },
  { canonicalName: 'CANMAKE', aliases: ['CANMAKE', 'キャンメイク'] },
  { canonicalName: 'CEZANNE', aliases: ['CEZANNE', 'セザンヌ'] },
  { canonicalName: 'excel', aliases: ['excel', 'エクセル'] },
  { canonicalName: 'KATE', aliases: ['KATE', 'ケイト'] },
  { canonicalName: 'Visee', aliases: ['Visee', 'ヴィセ'] },
  { canonicalName: 'MAQuillAGE', aliases: ['MAQuillAGE', 'マキアージュ'] },
  { canonicalName: 'ESPRIQUE', aliases: ['ESPRIQUE', 'エスプリーク'] },
  { canonicalName: 'INTEGRATE', aliases: ['INTEGRATE', 'インテグレート'] },
  { canonicalName: 'SUGAO', aliases: ['SUGAO', 'スガオ'] },
  { canonicalName: 'Fujiko', aliases: ['Fujiko', 'フジコ'] },
  { canonicalName: 'Love Liner', aliases: ['Love Liner', 'ラブライナー'] },
  { canonicalName: 'UZU BY FLOWFUSHI', aliases: ['UZU BY FLOWFUSHI', 'ウズ バイ フローフシ'] },
  { canonicalName: 'dejavu', aliases: ['dejavu', 'デジャヴュ'] },
  { canonicalName: 'ヒロインメイク', aliases: ['ヒロインメイク'] },
  { canonicalName: 'ettusais', aliases: ['ettusais', 'エテュセ'] },
  { canonicalName: 'ONLY MINERALS', aliases: ['ONLY MINERALS', 'オンリーミネラル'] },
  { canonicalName: 'bareMinerals', aliases: ['bareMinerals', 'ベアミネラル'] },
  { canonicalName: 'ETVOS', aliases: ['ETVOS', 'エトヴォス'] },
  { canonicalName: 'MiMC', aliases: ['MiMC', 'エムアイエムシー'] },
  { canonicalName: 'to/one', aliases: ['to/one', 'トーン'] },
  { canonicalName: 'Celvoke', aliases: ['Celvoke', 'セルヴォーク'] },
  { canonicalName: 'THREE', aliases: ['THREE', 'スリー'] },
  { canonicalName: 'shiro', aliases: ['shiro', 'シロ'] },
  { canonicalName: 'uka', aliases: ['uka', 'ウカ'] },
  { canonicalName: 'O.P.I', aliases: ['O.P.I', 'オーピーアイ'] },
  { canonicalName: 'NAIL HOLIC', aliases: ['NAIL HOLIC', 'ネイルホリック'] },
  { canonicalName: 'excel', aliases: ['excel', 'エクセル'] },
  { canonicalName: 'CANMAKE', aliases: ['CANMAKE', 'キャンメイク'] },
  { canonicalName: 'CEZANNE', aliases: ['CEZANNE', 'セザンヌ'] },
  { canonicalName: 'Fujiko', aliases: ['Fujiko', 'フジコ'] },
  { canonicalName: 'Wonjungyo', aliases: ['Wonjungyo', 'ウォンジョンヨ'] },
  { canonicalName: 'TIRTIR', aliases: ['TIRTIR', 'ティルティル'] },
  { canonicalName: 'rom&nd', aliases: ['rom&nd', 'ロムアンド'] },
  { canonicalName: 'ETUDE', aliases: ['ETUDE', 'エチュード'] },
  { canonicalName: 'CLIO', aliases: ['CLIO', 'クリオ'] },
  { canonicalName: 'hince', aliases: ['hince', 'ヒンス'] },
  { canonicalName: 'dasique', aliases: ['dasique', 'デイジーク'] },
  { canonicalName: 'AMUSE', aliases: ['AMUSE', 'アミューズ'] },
  { canonicalName: 'HERA', aliases: ['HERA', 'ヘラ'] },
  { canonicalName: 'LANEIGE', aliases: ['LANEIGE', 'ラネージュ'] },
  { canonicalName: 'innisfree', aliases: ['innisfree', 'イニスフリー'] },
  { canonicalName: 'ETUDE', aliases: ['ETUDE', 'エチュード'] },
  { canonicalName: 'MISSHA', aliases: ['MISSHA', 'ミシャ'] },
  { canonicalName: 'APIEU', aliases: ['APIEU', 'アピュー'] },
  { canonicalName: 'VT CICA', aliases: ['VT CICA', 'VTシカ'] },
  { canonicalName: 'Dr.Jart+', aliases: ['Dr.Jart+', 'ドクタージャルト'] },
  { canonicalName: 'Mediheal', aliases: ['Mediheal', 'メディヒール'] },
  { canonicalName: 'Abib', aliases: ['Abib', 'アビブ'] },
  { canonicalName: 'COSRX', aliases: ['COSRX', 'コスアールエックス'] },
  { canonicalName: 'SOME BY MI', aliases: ['SOME BY MI', 'サムバイミー'] },
  { canonicalName: 'Torriden', aliases: ['Torriden', 'トリデン'] },
  { canonicalName: 'BIOHEAL BOH', aliases: ['BIOHEAL BOH', 'バイオヒールボ'] },
  { canonicalName: 'goodal', aliases: ['goodal', 'グーダル'] },
  { canonicalName: 'ROUND LAB', aliases: ['ROUND LAB', 'ラウンドラボ'] },
  { canonicalName: 'Anua', aliases: ['Anua', 'アヌア'] },
  { canonicalName: 'ナンバーズイン', aliases: ['ナンバーズイン'] },
  { canonicalName: '魔女工場', aliases: ['魔女工場'] },
  { canonicalName: 'VT CICA', aliases: ['VT CICA', 'VTシカ'] },
  { canonicalName: 'Dr.Jart+', aliases: ['Dr.Jart+', 'ドクタージャルト'] },
  { canonicalName: 'Mediheal', aliases: ['Mediheal', 'メディヒール'] },
  { canonicalName: 'Abib', aliases: ['Abib', 'アビブ'] },
  { canonicalName: 'COSRX', aliases: ['COSRX', 'コスアールエックス'] },
  { canonicalName: 'SOME BY MI', aliases: ['SOME BY MI', 'サムバイミー'] },
  { canonicalName: 'Torriden', aliases: ['Torriden', 'トリデン'] },
  { canonicalName: 'BIOHEAL BOH', aliases: ['BIOHEAL BOH', 'バイオヒールボ'] },
  { canonicalName: 'goodal', aliases: ['goodal', 'グーダル'] },
  { canonicalName: 'ROUND LAB', aliases: ['ROUND LAB', 'ラウンドラボ'] },
  { canonicalName: 'Anua', aliases: ['Anua', 'アヌア'] },
  { canonicalName: 'ナンバーズイン', aliases: ['ナンバーズイン'] },
  { canonicalName: '魔女工場', aliases: ['魔女工場'] },
];
